"""Visible CLI runner used by the GUI.

Every submitted line is a real, copyable ``python cli.py ...`` invocation.
The line is parsed into a program plus argv for QProcess; no command shell is
involved and no hidden arguments are appended.
"""

from __future__ import annotations

import json
import shlex
import subprocess
import sys
from collections import deque
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.error import URLError
from urllib.request import urlopen

from PyQt6.QtCore import QProcess, QTimer, Qt, pyqtSignal
from PyQt6.QtGui import QGuiApplication, QKeyEvent
from PyQt6.QtWidgets import (
    QFileDialog,
    QGroupBox,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QMessageBox,
    QPlainTextEdit,
    QPushButton,
    QSplitter,
    QTreeWidget,
    QTreeWidgetItem,
    QVBoxLayout,
    QWidget,
)

from commands.session_client import (
    HttpSessionClientError,
    read_http_session_state,
)


class CliCommandTextError(ValueError):
    pass


@dataclass(frozen=True)
class ParsedCliInvocation:
    original_text: str
    program: str
    arguments: list[str]
    command_name: str
    session_name: str | None


def parse_cli_invocation(command_text: str) -> ParsedCliInvocation:
    """Validate and split one GUI/script line without invoking a shell."""
    original = command_text.strip()
    if not original:
        raise CliCommandTextError("Command is empty.")

    try:
        tokens = [
            _remove_matching_outer_quotes(token)
            for token in shlex.split(original, posix=False)
        ]
    except ValueError as exc:
        raise CliCommandTextError(f"Invalid command quoting: {exc}") from exc
    if len(tokens) < 3:
        raise CliCommandTextError(
            "Expected a complete command such as: python cli.py --session gui status"
        )

    displayed_program = tokens[0]
    executable_name = Path(displayed_program).name.lower()
    allowed_python_names = {
        "python",
        "python.exe",
        "python3",
        "python3.exe",
        "py",
        "py.exe",
        Path(sys.executable).name.lower(),
    }
    if executable_name not in allowed_python_names:
        raise CliCommandTextError("The command must start with python or py.")
    program = (
        displayed_program
        if Path(displayed_program).is_absolute()
        else sys.executable
    )

    cli_token = tokens[1]
    if Path(cli_token).name.lower() != "cli.py":
        raise CliCommandTextError("The Python script must be cli.py.")

    cli_arguments = tokens[2:]
    session_name: str | None = None
    command_name: str | None = None
    i = 0
    while i < len(cli_arguments):
        token = cli_arguments[i]
        if token == "--session":
            if i + 1 >= len(cli_arguments):
                raise CliCommandTextError("--session requires a name.")
            session_name = cli_arguments[i + 1]
            i += 2
            continue
        if token.startswith("--session="):
            session_name = token.split("=", 1)[1]
            i += 1
            continue
        if not token.startswith("-") and command_name is None:
            command_name = token
        i += 1

    if not command_name:
        raise CliCommandTextError("The cli.py command name is missing.")

    return ParsedCliInvocation(
        original_text=original,
        program=program,
        arguments=[cli_token, *cli_arguments],
        command_name=command_name,
        session_name=session_name,
    )


def _remove_matching_outer_quotes(token: str) -> str:
    if len(token) >= 2 and token[0] == token[-1] and token[0] in ("'", '"'):
        return token[1:-1]
    return token


def build_copyable_cli_command(arguments_after_cli: list[str]) -> str:
    """Create the exact command text generated by GUI controls on Windows."""
    return subprocess.list2cmdline(["python", "cli.py", *arguments_after_cli])


def script_command_lines(script_text: str) -> list[str]:
    """Return executable CLI lines; only blank lines and # comments are skipped."""
    commands: list[str] = []
    for line_number, raw_line in enumerate(script_text.splitlines(), start=1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        try:
            parsed = parse_cli_invocation(line)
        except CliCommandTextError as exc:
            raise CliCommandTextError(f"Script line {line_number}: {exc}") from exc
        if parsed.command_name == "serve-http":
            raise CliCommandTextError(
                f"Script line {line_number}: serve-http is a long-running server "
                "command and cannot be part of a sequential script."
            )
        commands.append(line)
    return commands


CompletionCallback = Callable[[dict[str, Any] | None, int], None]


class CliHistoryLineEdit(QLineEdit):
    """Command input with terminal-like Up/Down history navigation."""

    def __init__(self, parent: QWidget | None = None) -> None:
        super().__init__(parent)
        self._history: list[str] = []
        self._history_index = 0
        self._draft_text = ""

    def remember(self, command_text: str) -> None:
        command = command_text.strip()
        if command and (not self._history or self._history[-1] != command):
            self._history.append(command)
        self._history_index = len(self._history)
        self._draft_text = ""

    def keyPressEvent(self, event: QKeyEvent) -> None:  # noqa: N802
        if event.key() == Qt.Key.Key_Up and self._history:
            if self._history_index == len(self._history):
                self._draft_text = self.text()
            self._history_index = max(0, self._history_index - 1)
            self.setText(self._history[self._history_index])
            return
        if event.key() == Qt.Key.Key_Down and self._history:
            self._history_index = min(len(self._history), self._history_index + 1)
            if self._history_index == len(self._history):
                self.setText(self._draft_text)
            else:
                self.setText(self._history[self._history_index])
            return
        super().keyPressEvent(event)


class CliConsolePanel(QWidget):
    """Terminal-like CLI panel with a named session and sequential scripts."""

    command_completed = pyqtSignal(str, int, object)
    busy_changed = pyqtSignal(bool)
    session_ready = pyqtSignal(str)

    def __init__(self, project_root: Path, parent: QWidget | None = None) -> None:
        super().__init__(parent)
        self._project_root = Path(project_root).resolve()
        self._active_process: QProcess | None = None
        self._cancel_process: QProcess | None = None
        self._server_process: QProcess | None = None
        self._server_history_item: QTreeWidgetItem | None = None
        self._active_history_item: QTreeWidgetItem | None = None
        self._active_command_text = ""
        self._active_stdout = ""
        self._active_stderr = ""
        self._active_callback: CompletionCallback | None = None
        self._script_queue: deque[str] = deque()
        self._script_stop_on_error = True
        self._server_ready_callbacks: list[Callable[[], None]] = []
        self._server_health_attempts = 0
        self._owned_session_names: set[str] = set()

        self._build_ui()
        QTimer.singleShot(0, self._auto_start_default_session)

    def _build_ui(self) -> None:
        session_group = QGroupBox("CLI session")
        session_layout = QHBoxLayout(session_group)
        self.session_name_line_edit = QLineEdit("gui")
        self.session_name_line_edit.setPlaceholderText("Session name")
        self.create_session_button = QPushButton("Create")
        self.attach_session_button = QPushButton("Attach")
        self.stop_session_button = QPushButton("Stop")
        self.session_status_label = QLabel("Not attached")
        session_layout.addWidget(QLabel("Name:"))
        session_layout.addWidget(self.session_name_line_edit)
        session_layout.addWidget(self.create_session_button)
        session_layout.addWidget(self.attach_session_button)
        session_layout.addWidget(self.stop_session_button)
        session_layout.addWidget(self.session_status_label, stretch=1)

        self.command_history_tree = QTreeWidget()
        self.command_history_tree.setHeaderLabels(
            ["Status", "Command", "Exit code"]
        )
        self.command_history_tree.setColumnWidth(0, 90)
        self.command_history_tree.setColumnWidth(1, 720)
        self.command_history_tree.itemDoubleClicked.connect(
            self._copy_history_item_to_input
        )

        self.command_line_edit = CliHistoryLineEdit()
        self.command_line_edit.setPlaceholderText(
            "python cli.py --session gui status"
        )
        self.run_button = QPushButton("Run")
        self.copy_button = QPushButton("Copy")
        command_row = QHBoxLayout()
        command_row.addWidget(QLabel(">"))
        command_row.addWidget(self.command_line_edit, stretch=1)
        command_row.addWidget(self.run_button)
        command_row.addWidget(self.copy_button)

        self.script_editor = QPlainTextEdit()
        self.script_editor.setPlaceholderText(
            "# One copyable command per line\n"
            "python cli.py --session gui status"
        )
        self.load_script_button = QPushButton("Load script...")
        self.save_script_button = QPushButton("Save script...")
        self.run_script_button = QPushButton("Run script")
        self.stop_script_button = QPushButton("Stop after current command")
        script_buttons = QHBoxLayout()
        script_buttons.addWidget(self.load_script_button)
        script_buttons.addWidget(self.save_script_button)
        script_buttons.addWidget(self.run_script_button)
        script_buttons.addWidget(self.stop_script_button)
        script_buttons.addStretch(1)

        script_widget = QWidget()
        script_layout = QVBoxLayout(script_widget)
        script_layout.setContentsMargins(0, 0, 0, 0)
        script_layout.addWidget(QLabel("CLI script"))
        script_layout.addWidget(self.script_editor)
        script_layout.addLayout(script_buttons)

        self.output_text_edit = QPlainTextEdit()
        self.output_text_edit.setReadOnly(True)
        output_widget = QWidget()
        output_layout = QVBoxLayout(output_widget)
        output_layout.setContentsMargins(0, 0, 0, 0)
        output_layout.addWidget(QLabel("Process output"))
        output_layout.addWidget(self.output_text_edit)

        lower_splitter = QSplitter()
        lower_splitter.addWidget(script_widget)
        lower_splitter.addWidget(output_widget)
        lower_splitter.setSizes([300, 400])

        layout = QVBoxLayout(self)
        layout.addWidget(session_group)
        layout.addWidget(QLabel("Executed commands — double-click to reuse"))
        layout.addWidget(self.command_history_tree, stretch=1)
        layout.addLayout(command_row)
        layout.addWidget(lower_splitter, stretch=1)

        self.create_session_button.clicked.connect(self.create_named_session)
        self.attach_session_button.clicked.connect(self.attach_named_session)
        self.stop_session_button.clicked.connect(self.stop_named_session)
        self.run_button.clicked.connect(self.run_command_from_input)
        self.command_line_edit.returnPressed.connect(self.run_command_from_input)
        self.copy_button.clicked.connect(self.copy_current_command)
        self.load_script_button.clicked.connect(self.load_script)
        self.save_script_button.clicked.connect(self.save_script)
        self.run_script_button.clicked.connect(self.run_script)
        self.stop_script_button.clicked.connect(self.stop_script)

    def _session_name(self) -> str:
        return self.session_name_line_edit.text().strip()

    @property
    def is_command_running(self) -> bool:
        return self._active_process is not None

    def build_session_command(self, command_name: str, *arguments: str) -> str:
        return self._session_command(command_name, *arguments)

    def execute_session_command(
        self,
        command_name: str,
        arguments: list[str] | None = None,
        completion_callback: CompletionCallback | None = None,
    ) -> bool:
        try:
            command = self._session_command(command_name, *(arguments or []))
        except CliCommandTextError as exc:
            QMessageBox.warning(self, "Session", str(exc))
            return False
        return self.execute_command(command, completion_callback)

    def request_session_cancel(self) -> bool:
        """Run the copyable CLI cancel command alongside the active command."""
        if self._cancel_process is not None:
            QMessageBox.information(
                self, "Cancel", "A cancellation request is already running."
            )
            return False
        try:
            command = self._session_command("cancel")
            parsed = parse_cli_invocation(command)
        except CliCommandTextError as exc:
            QMessageBox.warning(self, "Cancel", str(exc))
            return False

        history_item = QTreeWidgetItem(["Running", command, ""])
        self.command_history_tree.addTopLevelItem(history_item)
        self.command_history_tree.scrollToItem(history_item)
        self._append_output(f"> {command}\n")

        process = QProcess(self)
        process.setWorkingDirectory(str(self._project_root))
        output = {"stdout": "", "stderr": "", "finalized": False}

        def read_stdout() -> None:
            text = bytes(process.readAllStandardOutput()).decode(
                "utf-8", errors="replace"
            )
            output["stdout"] += text
            self._append_output(text)

        def read_stderr() -> None:
            text = bytes(process.readAllStandardError()).decode(
                "utf-8", errors="replace"
            )
            output["stderr"] += text
            self._append_output(text)

        def finalize(exit_code: int) -> None:
            if output["finalized"]:
                return
            output["finalized"] = True
            read_stdout()
            read_stderr()
            history_item.setText(0, "OK" if exit_code == 0 else "Failed")
            history_item.setText(2, str(exit_code))
            payload: dict[str, Any] | None = None
            try:
                decoded = json.loads(output["stdout"]) if output["stdout"].strip() else None
                if isinstance(decoded, dict):
                    payload = decoded
            except json.JSONDecodeError:
                pass
            self._cancel_process = None
            self._append_output(f"[exit code {exit_code}]\n\n")
            self.command_completed.emit(command, exit_code, payload)

        def process_error(error) -> None:
            message = f"Cancel process error: {process.errorString()}\n"
            output["stderr"] += message
            self._append_output(message)
            if error == QProcess.ProcessError.FailedToStart:
                finalize(127)

        process.readyReadStandardOutput.connect(read_stdout)
        process.readyReadStandardError.connect(read_stderr)
        process.finished.connect(lambda exit_code, _status: finalize(exit_code))
        process.errorOccurred.connect(process_error)
        self._cancel_process = process
        process.start(parsed.program, parsed.arguments)
        return True

    def _session_command(self, command_name: str, *arguments: str) -> str:
        name = self._session_name()
        if not name:
            raise CliCommandTextError("Enter a session name first.")
        return build_copyable_cli_command(
            ["--session", name, command_name, *arguments]
        )

    def _auto_start_default_session(self) -> None:
        self._ensure_http_server(self._attach_or_create_named_session)

    def _http_server_is_healthy(self) -> bool:
        try:
            with urlopen("http://127.0.0.1:8000/health", timeout=0.25) as response:
                return 200 <= int(response.status) < 300
        except (OSError, URLError):
            return False

    def _ensure_http_server(self, callback: Callable[[], None]) -> None:
        if self._http_server_is_healthy():
            callback()
            return
        self._server_ready_callbacks.append(callback)
        if self._server_process is not None:
            return

        command = build_copyable_cli_command(
            ["serve-http", "--host", "127.0.0.1", "--port", "8000"]
        )
        parsed = parse_cli_invocation(command)
        self._append_output(f"> {command}\n")
        self._server_history_item = QTreeWidgetItem(["Starting", command, ""])
        self.command_history_tree.addTopLevelItem(self._server_history_item)

        process = QProcess(self)
        process.setWorkingDirectory(str(self._project_root))
        process.readyReadStandardOutput.connect(self._read_server_stdout)
        process.readyReadStandardError.connect(self._read_server_stderr)
        process.finished.connect(self._server_process_finished)
        process.errorOccurred.connect(self._server_process_error)
        self._server_process = process
        process.start(parsed.program, parsed.arguments)
        self._server_health_attempts = 0
        QTimer.singleShot(150, self._poll_server_health)

    def _poll_server_health(self) -> None:
        if self._http_server_is_healthy():
            if self._server_history_item is not None:
                self._server_history_item.setText(0, "Running")
            callbacks = self._server_ready_callbacks
            self._server_ready_callbacks = []
            for callback in callbacks:
                callback()
            return
        self._server_health_attempts += 1
        if self._server_health_attempts >= 40:
            self._server_ready_callbacks = []
            self.session_status_label.setText("HTTP server failed to start")
            QMessageBox.critical(
                self,
                "HTTP server",
                "serve-http did not become ready on 127.0.0.1:8000.",
            )
            return
        QTimer.singleShot(150, self._poll_server_health)

    def _read_server_stdout(self) -> None:
        if self._server_process is not None:
            text = bytes(self._server_process.readAllStandardOutput()).decode(
                "utf-8", errors="replace"
            )
            self._append_output(text)

    def _read_server_stderr(self) -> None:
        if self._server_process is not None:
            text = bytes(self._server_process.readAllStandardError()).decode(
                "utf-8", errors="replace"
            )
            self._append_output(text)

    def _server_process_finished(self, exit_code: int, _status) -> None:
        if self._server_history_item is not None:
            self._server_history_item.setText(0, "Stopped")
            self._server_history_item.setText(2, str(exit_code))
        self._server_process = None

    def _server_process_error(self, _error) -> None:
        if self._server_process is not None:
            self._append_output(
                f"serve-http process error: {self._server_process.errorString()}\n"
            )

    def _attach_or_create_named_session(self) -> None:
        session_name = self._session_name()
        try:
            stored_state = read_http_session_state(
                self._project_root, session_name=session_name
            )
        except HttpSessionClientError as exc:
            self.session_status_label.setText(str(exc))
            return
        if stored_state is None:
            self.create_named_session()
            return
        if not self._stored_server_session_is_live(stored_state):
            self.create_named_session()
            return
        self._check_named_session(auto_create=True)

    def _stored_server_session_is_live(self, stored_state: dict[str, Any]) -> bool:
        base_url = str(stored_state.get("base_url") or "").rstrip("/")
        expected_id = str(stored_state.get("session_id") or "")
        if not base_url or not expected_id:
            return False
        try:
            with urlopen(f"{base_url}/sessions", timeout=0.5) as response:
                payload = json.loads(response.read().decode("utf-8"))
        except (OSError, URLError, json.JSONDecodeError):
            return False
        sessions = payload.get("sessions") if isinstance(payload, dict) else None
        if not isinstance(sessions, list):
            return False
        return any(
            isinstance(item, dict) and str(item.get("session_id") or "") == expected_id
            for item in sessions
        )

    def _check_named_session(self, *, auto_create: bool) -> None:
        session_name = self._session_name()
        try:
            command = self._session_command("status")
        except CliCommandTextError as exc:
            self.session_status_label.setText(str(exc))
            return

        def after_status(payload: dict[str, Any] | None, exit_code: int) -> None:
            if exit_code == 0:
                self.session_status_label.setText(f"Attached: {session_name}")
                self.session_ready.emit(session_name)
                return
            error = str((payload or {}).get("error") or "")
            if auto_create and (
                "No active HTTP session" in error or "HTTP 404" in error
            ):
                self.create_named_session()
            else:
                self.session_status_label.setText("Attach failed")

        self.execute_command(command, after_status)

    def create_named_session(self) -> None:
        session_name = self._session_name()
        try:
            command = self._session_command("serve")
        except CliCommandTextError as exc:
            QMessageBox.warning(self, "Session", str(exc))
            return

        def after_create(_payload: dict[str, Any] | None, exit_code: int) -> None:
            if exit_code == 0:
                self._owned_session_names.add(session_name)
                self.session_status_label.setText(f"Created: {session_name}")
                self.session_ready.emit(session_name)
            else:
                self.session_status_label.setText("Create failed")

        def run_create() -> None:
            self.execute_command(
                command,
                after_create,
            )

        self._ensure_http_server(run_create)

    def attach_named_session(self) -> None:
        self._ensure_http_server(
            lambda: self._check_named_session(auto_create=False)
        )

    def stop_named_session(self) -> None:
        session_name = self._session_name()
        try:
            command = self._session_command("serve-stop")
        except CliCommandTextError as exc:
            QMessageBox.warning(self, "Session", str(exc))
            return
        def after_stop(_payload: dict[str, Any] | None, exit_code: int) -> None:
            if exit_code == 0:
                self._owned_session_names.discard(session_name)
                self.session_status_label.setText("Stopped")
            else:
                self.session_status_label.setText("Stop failed")

        self.execute_command(command, after_stop)

    def run_command_from_input(self) -> None:
        self.execute_command(self.command_line_edit.text())

    def execute_command(
        self,
        command_text: str,
        completion_callback: CompletionCallback | None = None,
    ) -> bool:
        if self._active_process is not None:
            QMessageBox.information(
                self, "CLI busy", "Wait for the current command to finish."
            )
            return False
        try:
            parsed = parse_cli_invocation(command_text)
        except CliCommandTextError as exc:
            QMessageBox.warning(self, "Invalid CLI command", str(exc))
            return False

        self.command_line_edit.setText(parsed.original_text)
        self.command_line_edit.remember(parsed.original_text)
        self._active_command_text = parsed.original_text
        self._active_stdout = ""
        self._active_stderr = ""
        self._active_callback = completion_callback
        self._active_history_item = QTreeWidgetItem(
            ["Running", parsed.original_text, ""]
        )
        self.command_history_tree.addTopLevelItem(self._active_history_item)
        self.command_history_tree.scrollToItem(self._active_history_item)
        self._append_output(f"> {parsed.original_text}\n")

        process = QProcess(self)
        process.setWorkingDirectory(str(self._project_root))
        process.readyReadStandardOutput.connect(self._read_command_stdout)
        process.readyReadStandardError.connect(self._read_command_stderr)
        process.finished.connect(self._command_process_finished)
        process.errorOccurred.connect(self._command_process_error)
        self._active_process = process
        self._set_command_controls_busy(True)
        process.start(parsed.program, parsed.arguments)
        return True

    def _read_command_stdout(self) -> None:
        if self._active_process is None:
            return
        text = bytes(self._active_process.readAllStandardOutput()).decode(
            "utf-8", errors="replace"
        )
        self._active_stdout += text
        self._append_output(text)

    def _read_command_stderr(self) -> None:
        if self._active_process is None:
            return
        text = bytes(self._active_process.readAllStandardError()).decode(
            "utf-8", errors="replace"
        )
        self._active_stderr += text
        self._append_output(text)

    def _command_process_error(self, error) -> None:
        if self._active_process is not None:
            message = f"Process error: {self._active_process.errorString()}\n"
            self._active_stderr += message
            self._append_output(message)
            if error == QProcess.ProcessError.FailedToStart:
                self._finalize_active_process(127)

    def _command_process_finished(self, exit_code: int, _status) -> None:
        self._finalize_active_process(exit_code)

    def _finalize_active_process(self, exit_code: int) -> None:
        if self._active_process is None:
            return
        self._read_command_stdout()
        self._read_command_stderr()
        if self._active_history_item is not None:
            self._active_history_item.setText(0, "OK" if exit_code == 0 else "Failed")
            self._active_history_item.setText(2, str(exit_code))

        payload: dict[str, Any] | None = None
        try:
            decoded = json.loads(self._active_stdout) if self._active_stdout.strip() else None
            if isinstance(decoded, dict):
                payload = decoded
        except json.JSONDecodeError:
            pass

        command_text = self._active_command_text
        callback = self._active_callback
        self._active_process = None
        self._active_history_item = None
        self._active_callback = None
        self._set_command_controls_busy(False)
        self._append_output(f"[exit code {exit_code}]\n\n")
        self.command_completed.emit(command_text, exit_code, payload)
        if callback is not None:
            callback(payload, exit_code)

        if self._script_queue:
            if exit_code != 0 and self._script_stop_on_error:
                remaining = len(self._script_queue)
                self._script_queue.clear()
                self._append_output(
                    f"Script stopped after failure; {remaining} command(s) skipped.\n"
                )
            else:
                next_command = self._script_queue.popleft()
                QTimer.singleShot(0, lambda: self.execute_command(next_command))

    def _set_command_controls_busy(self, busy: bool) -> None:
        self.run_button.setEnabled(not busy)
        self.run_script_button.setEnabled(not busy)
        self.create_session_button.setEnabled(not busy)
        self.attach_session_button.setEnabled(not busy)
        self.stop_session_button.setEnabled(not busy)
        self.busy_changed.emit(busy)

    def copy_current_command(self) -> None:
        selected_item = self.command_history_tree.currentItem()
        text = (
            selected_item.text(1).strip()
            if selected_item is not None
            else self.command_line_edit.text().strip()
        )
        if text:
            QGuiApplication.clipboard().setText(text)

    def _copy_history_item_to_input(
        self, item: QTreeWidgetItem, _column: int
    ) -> None:
        command = item.text(1)
        self.command_line_edit.setText(command)
        QGuiApplication.clipboard().setText(command)

    def load_script(self) -> None:
        path, _ = QFileDialog.getOpenFileName(
            self,
            "Load CLI script",
            str(self._project_root),
            "CLI scripts (*.txt *.swscript);;All files (*.*)",
        )
        if not path:
            return
        try:
            text = Path(path).read_text(encoding="utf-8")
            script_command_lines(text)
        except (OSError, UnicodeError, CliCommandTextError) as exc:
            QMessageBox.warning(self, "Load script", str(exc))
            return
        self.script_editor.setPlainText(text)

    def save_script(self) -> None:
        try:
            script_command_lines(self.script_editor.toPlainText())
        except CliCommandTextError as exc:
            QMessageBox.warning(self, "Save script", str(exc))
            return
        path, _ = QFileDialog.getSaveFileName(
            self,
            "Save CLI script",
            str(self._project_root / "commands.swscript"),
            "CLI scripts (*.swscript);;Text files (*.txt);;All files (*.*)",
        )
        if not path:
            return
        try:
            Path(path).write_text(self.script_editor.toPlainText(), encoding="utf-8")
        except OSError as exc:
            QMessageBox.critical(self, "Save script", str(exc))

    def run_script(self) -> None:
        if self._active_process is not None:
            QMessageBox.information(self, "CLI busy", "A command is already running.")
            return
        try:
            commands = script_command_lines(self.script_editor.toPlainText())
        except CliCommandTextError as exc:
            QMessageBox.warning(self, "Invalid script", str(exc))
            return
        if not commands:
            QMessageBox.information(self, "CLI script", "The script has no commands.")
            return
        self._script_queue = deque(commands[1:])
        self.execute_command(commands[0])

    def stop_script(self) -> None:
        skipped = len(self._script_queue)
        self._script_queue.clear()
        self._append_output(
            f"Script will stop after the current command; {skipped} queued command(s) removed.\n"
        )

    def _append_output(self, text: str) -> None:
        if not text:
            return
        cursor = self.output_text_edit.textCursor()
        cursor.movePosition(cursor.MoveOperation.End)
        cursor.insertText(text)
        self.output_text_edit.setTextCursor(cursor)
        self.output_text_edit.ensureCursorVisible()

    def shutdown(self) -> None:
        self._script_queue.clear()
        if self._cancel_process is not None:
            self._cancel_process.terminate()
            self._cancel_process.waitForFinished(1000)
            if self._cancel_process is not None:
                self._cancel_process.kill()
        if self._active_process is not None:
            self._active_process.terminate()
            self._active_process.waitForFinished(1500)
            if self._active_process is not None:
                self._active_process.kill()
        if self._http_server_is_healthy():
            for session_name in sorted(self._owned_session_names):
                command = build_copyable_cli_command(
                    ["--session", session_name, "serve-stop"]
                )
                parsed = parse_cli_invocation(command)
                close_process = QProcess()
                close_process.setWorkingDirectory(str(self._project_root))
                close_process.start(parsed.program, parsed.arguments)
                close_process.waitForFinished(3000)
        self._owned_session_names.clear()
        if self._server_process is not None:
            self._server_process.terminate()
            self._server_process.waitForFinished(2000)
            if self._server_process is not None:
                self._server_process.kill()
